### ISSUE TITLE
Remove unnecessary adding of low aces

### ISSUE THREAD

**Issue by sodoku** [camilleldn/peer-to-peer-poker#1]
In
https://github.com/camilleldn/peer-to-peer-poker/blob/master/lib/hand.rb#L76-L87
the ammount of aces is checked in the ranking for a straight, but a hand with more than one ace (or any oder pip) can never be a straight.

**Comment by camillebaldock** [comment]
Thank you very much for your feedback! :thumbsup: I'll take a look at correcting that this evening :-)

**Comment by camillebaldock** [comment]
This is a great point by @sodoku. The master branch is exactly what was done in the podcast so I will leave it as is to keep all its problems and imperfections for posterity. Thanks again :+1:
